processorTypes:
  - org.apache.nifi.processors.standard.ExecuteSQL:
      SQL Query: sql_query.sql
  - org.apache.nifi.processors.standard.ExecuteSQLRecord:
      SQL Query: sql_query.sql
  - org.apache.nifi.processors.standard.QueryDatabaseTable:
      Custom Query: custom_query.sql
  - org.apache.nifi.processors.standard.QueryDatabaseTableRecord:
      Custom Query: custom_query.sql
  - org.qubership.nifi.processors.extract.QueryDatabaseToCSV:
      custom-query: custom_query.sql
  - org.qubership.nifi.processors.QueryDatabaseToJson:
      db-fetch-sql-query: sql_query.sql
  - org.qubership.nifi.processors.QueryDatabaseToJsonWithMerge:
      db-fetch-sql-query: sql_query.sql
  - org.qubership.nifi.processors.QueryIdsAndFetchTableToJson:
      custom-query: custom_query.sql
  - org.apache.nifi.processors.standard.PutSQL:
      SQL Statement: sql_statement.sql
  - org.qubership.nifi.processors.PutSQLRecord:
      sql-statement: sql_statement.sql
  - org.qubership.nifi.processors.FetchTableToJson:
      custom-query: custom_query.sql
  - org.apache.nifi.processors.groovyx.ExecuteGroovyScript:
      Script Body: script_body.groovy
  - org.apache.nifi.processors.script.ExecuteScript:
      Script Body: script_body.groovy
  - org.apache.nifi.processors.script.InvokeScriptedProcessor:
      Script Body: script_body.groovy
  - org.apache.nifi.processors.script.ScriptedTransformRecord:
      Script Body: script_body.groovy
  - org.qubership.nifi.processors.PostgreSQLBulkLoader:
      sql-query: sql_query.sql
  - org.apache.nifi.processors.jolt.JoltTransformJSON:
      Jolt Specification: jolt_spec.json
  - org.apache.nifi.processors.jolt.JoltTransformRecord:
      Jolt Specification: jolt_spec.json
