---
name: 'Run configuration restore tests'
description: 'Run configuration restore tests'
inputs:
  results-dir:
    description: 'Directory to store results'
    required: false
    default: 'plain'
  docker-compose-path:
    description: 'Path to docker compose file'
    required: false
    default: ''
  tls-mode:
    description: 'NiFi run Mode'
    required: false
    type: boolean
    default: false
runs:
  using: "composite"
  steps:
    - name: Getting the flow.json.gz version from the archive folder
      shell: bash
      continue-on-error: true
      run: |
        . .github/workflows/sh/nifi-lib.sh
        get_flow_json_version
    - name: Creating a test process group
      continue-on-error: true
      uses: ./.github/actions/run-newman-tests
      with:
        collection-name: 'NiFi_Check_Config_Restore_Create_PG.postman_collection.json'
        env-name: 'NiFi_AT.json.postman_environment'
        results-dir: '${{ inputs.results-dir }}'
        short-name: 'create_pg'
    - name: Set the version in Consul
      shell: bash
      continue-on-error: true
      run: |
        . .github/workflows/sh/nifi-lib.sh
        export CONF_VERSION=$(cat ./nifi-conf-version.tmp)
        set_configuration_version '$CONF_VERSION'
    - name: Restart local nifi
      shell: bash
      run: |
        export NIFI_SENSITIVE_KEY=$(cat ./nifi-sens-key.tmp)
        echo "Restarting containers..."
        docker-compose restart nifi
    - name: Wait for nifi container to start
      shell: bash
      continue-on-error: true
      run: |
        . .github/workflows/sh/nifi-lib.sh
        wait_nifi_container "15" "60" "127.0.0.1" "8080" "false" "local-nifi-plain" "${{ inputs.results-dir }}"
    - name: Checking that the version has been restored
      continue-on-error: true
      uses: ./.github/actions/run-newman-tests
      with:
        collection-name: 'NiFi_Check_Config_Restore_Check_PG.postman_collection.json'
        env-name: 'NiFi_AT.json.postman_environment'
        results-dir: '${{ inputs.results-dir }}'
        short-name: 'check_pg'
