---
name: 'Run configuration restore tests'
description: 'Run configuration restore tests'
inputs:
  results-dir:
    description: 'Directory to store results'
    required: false
    default: 'tls'
  docker-compose-path:
    description: 'Path to docker compose file'
    required: false
    default: ''
  success-scenario:
    description: 'NiFi run Mode'
    required: true
    default: true
runs:
  using: "composite"
  steps:
    - name: Getting the flow.json.gz version from the archive folder (success scenario)
      if: ${{ inputs.success-scenario == 'true' }}
      shell: bash
      continue-on-error: true
      run: |
        . .github/workflows/sh/nifi-lib.sh
        get_flow_json_version "${{ inputs.docker-compose-path }}"
    - name: Getting the flow.json.gz version from the archive folder (error scenario)
      if: ${{ inputs.success-scenario == 'false' }}
      shell: bash
      continue-on-error: true
      run: |
        . .github/workflows/sh/nifi-lib.sh
        get_flow_json_version_error
    - name: Creating a test process group
      continue-on-error: true
      uses: ./.github/actions/run-newman-tests
      with:
        collection-name: 'NiFi_Check_Config_Restore_Create_PG.postman_collection.json'
        env-name: 'NiFi_AT_TLS.json.postman_environment'
        results-dir: '${{ inputs.results-dir }}'
        short-name: 'create_pg_before_restore'
        tls-certs-dir: "./temp-vol/tls-cert"
        tls-ca-certs: "nifi/nifi-cert.pem"
        tls-client-certs-config: "newman-tls-config.json"
        docker-compose-file: '${{ inputs.docker-compose-path }}'
    - name: Set the version in Consul
      shell: bash
      continue-on-error: true
      run: |
        . .github/workflows/sh/nifi-lib.sh
        export CONF_VERSION=$(cat ./nifi-conf-version.tmp)
        [ -f ./consul-acl-token.tmp ] && CONSUL_TOKEN=$(cat ./consul-acl-token.tmp)
        set_configuration_version "$CONF_VERSION" "$CONSUL_TOKEN"
    - name: Restart local NiFi and wait for health
      shell: bash
      run: |
        export NIFI_SENSITIVE_KEY=$(cat ./nifi-sens-key.tmp)
        echo "Restarting containers..."
        docker compose -f ${{ inputs.docker-compose-path }} --env-file ./docker.env restart nifi
        docker compose -f ${{ inputs.docker-compose-path }} --env-file ./docker.env \
          up -d --wait --wait-timeout 75 nifi
    - name: Checking that the version has been restored and the created process group does not exist
      if: ${{ inputs.success-scenario == 'true' }}
      continue-on-error: true
      uses: ./.github/actions/run-newman-tests
      with:
        collection-name: 'NiFi_Check_Config_Restore_Check_PG_Not_Exists.postman_collection.json'
        env-name: 'NiFi_AT_TLS.json.postman_environment'
        results-dir: '${{ inputs.results-dir }}'
        short-name: 'check_pg_after_success_restore'
        tls-certs-dir: "./temp-vol/tls-cert"
        tls-ca-certs: "nifi/nifi-cert.pem"
        tls-client-certs-config: "newman-tls-config.json"
        docker-compose-file: '${{ inputs.docker-compose-path }}'
    - name: Checking that the version has been restored and the created process group exists
      if: ${{ inputs.success-scenario == 'false' }}
      continue-on-error: true
      uses: ./.github/actions/run-newman-tests
      with:
        collection-name: 'NiFi_Check_Config_Restore_Check_PG_Exists.postman_collection.json'
        env-name: 'NiFi_AT_TLS.json.postman_environment'
        results-dir: '${{ inputs.results-dir }}'
        short-name: 'check_pg_after_failed_restore'
        tls-certs-dir: "./temp-vol/tls-cert"
        tls-ca-certs: "nifi/nifi-cert.pem"
        tls-client-certs-config: "newman-tls-config.json"
        docker-compose-file: '${{ inputs.docker-compose-path }}'
