---
services:
  nifi:
    image: local-nifi:test
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - nifi-conf:/opt/nifi/nifi-current/persistent_conf
    environment:
      - NAMESPACE=local
      - CONSUL_ENABLED=true
      - CONSUL_URL=consul:8500
      - AUTH=none
      - NIFI_NEW_SENSITIVE_KEY=${NIFI_SENSITIVE_KEY}
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTPS_PORT=
    container_name: local-nifi
  nifi-registry:
    image: ghcr.io/netcracker/qubership-nifi-registry:latest
    ports:
      - 127.0.0.1:18080:18080
    environment:
      - AUTH=none
    container_name: local-nifi-registry
    hostname: nifi-registry
  consul:
    image: hashicorp/consul:1.20
    ports:
      - 127.0.0.1:8500:8500
    hostname: consul
volumes:
  nifi-conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $BASE_DIR/temp-vol/nifi/per-conf/
