---
name: Docker build and test

on:
  push:
    paths:
      - '.github/workflows/docker-build-and-test.yml'
      - 'qubership-bundle/**'
      - 'qubership-consul/**'
      - 'qubership-nifi-bulk-redis-service/**'
      - 'qubership-nifi-bundle-common/**'
      - 'qubership-nifi-common/**'
      - 'qubership-nifi-db-bundle/**'
      - 'qubership-nifi-lookup-services/**'
      - 'qubership-services/**'
      - 'pom.xml'
      - 'Dockerfile'
      - 'nifi-config/**'
      - 'nifi-scripts/**'
      - 'qubership-nifi-deps/**'
      - 'scripts/**'
      - '.github/actions/**'
      - '.github/collections/**'
      - '.github/workflows/sh/**'
  pull_request:
    paths:
      - '.github/workflows/docker-build-and-test.yml'
      - 'qubership-bundle/**'
      - 'qubership-consul/**'
      - 'qubership-nifi-bulk-redis-service/**'
      - 'qubership-nifi-bundle-common/**'
      - 'qubership-nifi-common/**'
      - 'qubership-nifi-db-bundle/**'
      - 'qubership-nifi-lookup-services/**'
      - 'qubership-services/**'
      - 'pom.xml'
      - 'Dockerfile'
      - 'nifi-config/**'
      - 'nifi-scripts/**'
      - 'qubership-nifi-deps/**'
      - 'scripts/**'
      - '.github/actions/**'
      - '.github/collections/**'
      - '.github/workflows/sh/**'
  workflow_dispatch:
    inputs:
      java-version:
        required: false
        type: string
        default: "21"
        description: 'Java version (e.g., 21)'
jobs:
  mvn:
    uses: ./.github/workflows/maven-build-and-test.yml
    with:
      java-version: ${{ github.event.inputs.java-version || '21' }}
      artifact-id: 'qubership-nifi-local-build'
      upload-artifact: true
      skip-sonar: true
  docker-build-and-test:
    needs: [ mvn ]
    runs-on: ubuntu-latest
    steps:
      - name: Input parameters
        shell: bash
        run: |
          echo "Java version: ${{ github.event.inputs.java-version || '21' }}" >> $GITHUB_STEP_SUMMARY
          mkdir -p ./test-results/
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: 'qubership-nifi-local-build'
      - name: Run local docker build
        run: docker build -t local-nifi:test .
      - name: Run tests for nifi in plain (non-TLS mode)
        uses: ./.github/actions/run-nifi-tests-plain
      - name: Run tests for nifi in TLS mode
        uses: ./.github/actions/run-nifi-tests-tls
      - name: Run tests for nifi in TLS and OIDC mode
        uses: ./.github/actions/run-nifi-tests-oidc
      - name: Verify test results
        shell: bash
        run: |
          echo "Checking test results for failures..."
          failed_cnt=$(find ./test-results -name "failed_*.lst" | wc -l)
          echo "Found failed steps = $failed_cnt"
          if [ "$failed_cnt" == "0" ]; then 
            echo "All tests were successful!"
          else
            echo "Some tests ($failed_cnt) failed. Marking as failure."
            exit 1;
          fi
      - name: Upload test results
        if: failure() || cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: nifi-autotests-logs
          path: |
            ./test-results
          retention-days: 2
      
