---
name: docker-build-and-test

on:
  push:
    paths:
      - '.github/workflows/docker-build-and-test.yml'
      - 'qubership-bundle/**'
      - 'qubership-consul/**'
      - 'qubership-nifi-bulk-redis-service/**'
      - 'qubership-nifi-bundle-common/**'
      - 'qubership-nifi-common/**'
      - 'qubership-nifi-db-bundle/**'
      - 'qubership-nifi-lookup-services/**'
      - 'qubership-services/**'
      - 'pom.xml'
      - 'Dockerfile'
      - 'nifi-config/**'
      - 'nifi-scripts/**'
      - 'qubership-nifi-deps/**'
      - 'scripts/**'
      - '.github/actions/**'
      - '.github/collections/**'
      - '.github/workflows/sh/**'
      - '.github/docker/**'
      - '.github/configuration/**'
  pull_request:
    paths:
      - '.github/workflows/docker-build-and-test.yml'
      - 'qubership-bundle/**'
      - 'qubership-consul/**'
      - 'qubership-nifi-bulk-redis-service/**'
      - 'qubership-nifi-bundle-common/**'
      - 'qubership-nifi-common/**'
      - 'qubership-nifi-db-bundle/**'
      - 'qubership-nifi-lookup-services/**'
      - 'qubership-services/**'
      - 'pom.xml'
      - 'Dockerfile'
      - 'nifi-config/**'
      - 'nifi-scripts/**'
      - 'qubership-nifi-deps/**'
      - 'scripts/**'
      - '.github/actions/**'
      - '.github/collections/**'
      - '.github/workflows/sh/**'
      - '.github/docker/**'
      - '.github/configuration/**'
  workflow_dispatch:
    inputs:
      java-version:
        required: false
        type: string
        default: "21"
        description: 'Java version (e.g., 21)'

permissions:
  contents: read

jobs:
  mvn:
    uses: ./.github/workflows/maven-build-and-test.yml
    with:
      java-version: ${{ github.event.inputs.java-version || '21' }}
      artifact-id: 'qubership-nifi-local-build'
      upload-artifact: true
      skip-sonar: true
  docker-build-and-test:
    strategy:
      fail-fast: false
      matrix:
        run-mode: [ 'plain', 'tls', 'oidc', 'cluster' ]
    needs: [ mvn ]
    runs-on: ubuntu-latest
    steps:
      - name: Prepare test results
        shell: bash
        run: |
          mkdir -p ./test-results/
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: 'qubership-nifi-local-build'
      - name: Run local docker build
        run: docker build -t local-nifi:test .
      - name: Run tests with mode = ${{ matrix.run-mode }}
        uses: ./.github/actions/run-nifi-tests-generic
        with:
          run-mode: '${{ matrix.run-mode }}'
      - name: Verify test results
        shell: bash
        run: |
          echo "Checking test results for failures..."
          failed_cnt=$(find ./test-results -name "failed_*.lst" | wc -l)
          echo "Found failed steps = $failed_cnt"
          if [ "$failed_cnt" == "0" ]; then
            echo "All tests were successful!"
            echo "All tests were successful!" >> $GITHUB_STEP_SUMMARY
          else
            echo "Some tests ($failed_cnt) failed. Marking as failure."
            echo "Some tests ($failed_cnt) failed. Marking as failure." >> $GITHUB_STEP_SUMMARY
            exit 1;
          fi
      - name: Upload test results
        if: failure() || cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: nifi-autotests-${{ matrix.run-mode }}-logs
          path: |
            ./test-results
          retention-days: 2
