name: NiFi Docker Autotests

on:
  workflow_dispatch:
jobs:
  nifi-autotests:
    runs-on: ubuntu-latest
    services:
      consul:
        image: hashicorp/consul:1.20
        ports:
          - 8500:8500
        options: "-h consul"
      nifi:
        image: ghcr.io/netcracker/nifi:latest
        env:
          NAMESPACE: local
          CONSUL_ENABLED: "true"
          CONSUL_URL: "consul:8500"
          AUTH: none
          NIFI_NEW_SENSITIVE_KEY: Abcdefghjkl12
          NIFI_WEB_HTTP_PORT: 8080
          NIFI_WEB_HTTPS_PORT: ""
        ports:
          - 8080:8080
        options: "-h nifi --name local-nifi"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Display running containers
        shell: bash
        run: docker ps
      - name: Wait for nifi container to start
        shell: bash
        run: |
          echo "Preparing libs..."
          chmod +x .github/workflows/sh/*.sh
          . .github/workflows/sh/nifi-lib.sh
          echo "Display nifi logs:"
          docker logs local-nifi
          echo "Wait for nifi to start:"
          wait_for_nifi "false" "60" "127.0.0.1" "8080"
          echo "Display nifi logs:"
          docker logs local-nifi
      - name: Run nifi API tests
        shell: bash
        run: |
          echo "Running newman..."
          docker run  --net=host --rm -v ~/.github/workflows/collections:/etc/newman postman/newman:alpine run "NiFi Basic API Tests.postman_collection.json" --environment="NiFiLocal.json.postman_environment" -r cli,junit
      - name: Upload Test Results
        if: failure() || cancelled()
        uses: actions/upload-artifact@v4
        with:
          name: nifi-autotests-logs
          path: |
            **/target/failsafe-reports/**/*.xml
            .github/workflows/collections/*.xml
          retention-days: 2
      
