name: NiFi Docker Autotests

on:
  workflow_dispatch:
    inputs:
      java-version:
        required: false
        type: string
        default: "21"
        description: 'Java version (e.g., 21)'
jobs:
  nifi-autotests:
    runs-on: ubuntu-latest
    services:
      consul:
        image: hashicorp/consul:1.20
        ports:
          - 8500:8500
        options: "-h consul"
      local-registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Input parameters
        run: |
          echo "Java version: ${{ github.event.inputs.java-version }}"
      - name: Display running containers
        shell: bash
        run: docker ps
      - name: List docker image in local registry:
        run: |
          echo "Listing..."
          curl -X GET http://localhost:5000/v2/_catalog
          sleep 30
          reg_container_id=$(docker ps -a | grep 'registry:2' | awk '{print $1}')
          echo "Registry container id=$reg_container_id and its logs:"
          docker logs $reg_container_id
          echo "Listing..."
          curl -X GET http://localhost:5000/v2/_catalog
          sleep 30
          echo "Listing..."
          curl -X GET http://localhost:5000/v2/_catalog

